language: python
python:
  - 2.6
  - 2.7
  - pypy
install:
  - echo -e "[buildout]\nextends = buildout.d/development.cfg" > buildout.cfg
  - cp buildout.d/secrets.cfg.sample buildout.d/secrets.cfg
  - python bootstrap.py
  - bin/buildout
script:
  - ./run_tests.sh
notifications:
  irc:
    - "irc.sioff.net#kiberpipa"
